### ISSUE TITLE
Sending context data during location updates

### ISSUE THREAD

**Issue by punitda** [adobe/places-monitor-android#36]
When we start location monitoring by calling `PlacesMonitor.start()` method in sdk, is there any way in sdk to send some custom attributes by attaching them to contextData for every location update when user enters any poi location range? 
Sorry, if it is wrong place to ask this question.

**Comment by sbenedicadb** [comment]
Hey @punitda,

This is a great place to ask this question, my apologies for the delay in a response.  

When you say "send some custom attributes", do you mean to Analytics?  

If so, check out the documentation here, explaining two different ways you can get your location data to Analytics:
- [Send POI entry and exit data to Analytics](https://docs.adobe.com/content/help/en/places/using/use-places-with-other-solutions/places-adobe-analytics/use-places-adobe-analytics.html)
- [Add location context to Analytics requests](https://docs.adobe.com/content/help/en/places/using/use-places-with-other-solutions/places-adobe-analytics/run-reports-aa-places-data.html)

Hope this helps.  Let me know if you have further questions.  Thanks!

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)
