### ISSUE TITLE
PlacesMonitorOnBootReceiver - explicit value for android:exported be defined

### ISSUE THREAD

**Issue by woodenh** [adobe/places-monitor-android#55]
### Expected Behavior
PlacesMonitorOnBootReceiver should have explicit value for android:exported in AndroidManifest.xml to be targeted Android SDK 31

<receiver android:name="com.adobe.marketing.mobile.PlacesMonitorOnBootReceiver" **android:exported="true"**>
    <intent-filter>
        <action android:name="android.intent.action.BOOT_COMPLETED" />
    </intent-filter>
</receiver>

### Actual Behavior
- no compile/build time error
- runtime error:
Installation failed due to: 'INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2024741119.tmp/base.apk (at Binary XML file line #443): com.adobe.marketing.mobile.PlacesMonitorOnBootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

- 

#### Steps to Reproduce
build and run app which using **com.adobe.marketing.mobile:places-monitor** library with 
targetSdkVersion 31

**Comment by sbenedicadb** [comment]
fixed in 2.2.3
